// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIGetUserParams creates a new APIGetUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAPIGetUserParams() *APIGetUserParams {
	return &APIGetUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAPIGetUserParamsWithTimeout creates a new APIGetUserParams object
// with the ability to set a timeout on a request.
func NewAPIGetUserParamsWithTimeout(timeout time.Duration) *APIGetUserParams {
	return &APIGetUserParams{
		timeout: timeout,
	}
}

// NewAPIGetUserParamsWithContext creates a new APIGetUserParams object
// with the ability to set a context for a request.
func NewAPIGetUserParamsWithContext(ctx context.Context) *APIGetUserParams {
	return &APIGetUserParams{
		Context: ctx,
	}
}

// NewAPIGetUserParamsWithHTTPClient creates a new APIGetUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewAPIGetUserParamsWithHTTPClient(client *http.Client) *APIGetUserParams {
	return &APIGetUserParams{
		HTTPClient: client,
	}
}

/*
APIGetUserParams contains all the parameters to send to the API endpoint

	for the Api get user operation.

	Typically these are written to a http.Request.
*/
type APIGetUserParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the Api get user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIGetUserParams) WithDefaults() *APIGetUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the Api get user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIGetUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the Api get user params
func (o *APIGetUserParams) WithTimeout(timeout time.Duration) *APIGetUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api get user params
func (o *APIGetUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api get user params
func (o *APIGetUserParams) WithContext(ctx context.Context) *APIGetUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api get user params
func (o *APIGetUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api get user params
func (o *APIGetUserParams) WithHTTPClient(client *http.Client) *APIGetUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api get user params
func (o *APIGetUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the Api get user params
func (o *APIGetUserParams) WithID(id string) *APIGetUserParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the Api get user params
func (o *APIGetUserParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIGetUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
