// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAPIListUsersParams creates a new APIListUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAPIListUsersParams() *APIListUsersParams {
	return &APIListUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAPIListUsersParamsWithTimeout creates a new APIListUsersParams object
// with the ability to set a timeout on a request.
func NewAPIListUsersParamsWithTimeout(timeout time.Duration) *APIListUsersParams {
	return &APIListUsersParams{
		timeout: timeout,
	}
}

// NewAPIListUsersParamsWithContext creates a new APIListUsersParams object
// with the ability to set a context for a request.
func NewAPIListUsersParamsWithContext(ctx context.Context) *APIListUsersParams {
	return &APIListUsersParams{
		Context: ctx,
	}
}

// NewAPIListUsersParamsWithHTTPClient creates a new APIListUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewAPIListUsersParamsWithHTTPClient(client *http.Client) *APIListUsersParams {
	return &APIListUsersParams{
		HTTPClient: client,
	}
}

/*
APIListUsersParams contains all the parameters to send to the API endpoint

	for the Api list users operation.

	Typically these are written to a http.Request.
*/
type APIListUsersParams struct {

	// ID.
	ID []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the Api list users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIListUsersParams) WithDefaults() *APIListUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the Api list users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIListUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the Api list users params
func (o *APIListUsersParams) WithTimeout(timeout time.Duration) *APIListUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api list users params
func (o *APIListUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api list users params
func (o *APIListUsersParams) WithContext(ctx context.Context) *APIListUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api list users params
func (o *APIListUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api list users params
func (o *APIListUsersParams) WithHTTPClient(client *http.Client) *APIListUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api list users params
func (o *APIListUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the Api list users params
func (o *APIListUsersParams) WithID(id []string) *APIListUsersParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the Api list users params
func (o *APIListUsersParams) SetID(id []string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIListUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// binding items for id
		joinedID := o.bindParamID(reg)

		// query array param id
		if err := r.SetQueryParam("id", joinedID...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamAPIListUsers binds the parameter id
func (o *APIListUsersParams) bindParamID(formats strfmt.Registry) []string {
	iDIR := o.ID

	var iDIC []string
	for _, iDIIR := range iDIR { // explode []string

		iDIIV := iDIIR // string as string
		iDIC = append(iDIC, iDIIV)
	}

	// items.CollectionFormat: "multi"
	iDIS := swag.JoinByFormat(iDIC, "multi")

	return iDIS
}
