// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIDeleteUserParams creates a new APIDeleteUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAPIDeleteUserParams() *APIDeleteUserParams {
	return &APIDeleteUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAPIDeleteUserParamsWithTimeout creates a new APIDeleteUserParams object
// with the ability to set a timeout on a request.
func NewAPIDeleteUserParamsWithTimeout(timeout time.Duration) *APIDeleteUserParams {
	return &APIDeleteUserParams{
		timeout: timeout,
	}
}

// NewAPIDeleteUserParamsWithContext creates a new APIDeleteUserParams object
// with the ability to set a context for a request.
func NewAPIDeleteUserParamsWithContext(ctx context.Context) *APIDeleteUserParams {
	return &APIDeleteUserParams{
		Context: ctx,
	}
}

// NewAPIDeleteUserParamsWithHTTPClient creates a new APIDeleteUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewAPIDeleteUserParamsWithHTTPClient(client *http.Client) *APIDeleteUserParams {
	return &APIDeleteUserParams{
		HTTPClient: client,
	}
}

/*
APIDeleteUserParams contains all the parameters to send to the API endpoint

	for the Api delete user operation.

	Typically these are written to a http.Request.
*/
type APIDeleteUserParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the Api delete user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIDeleteUserParams) WithDefaults() *APIDeleteUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the Api delete user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIDeleteUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the Api delete user params
func (o *APIDeleteUserParams) WithTimeout(timeout time.Duration) *APIDeleteUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api delete user params
func (o *APIDeleteUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api delete user params
func (o *APIDeleteUserParams) WithContext(ctx context.Context) *APIDeleteUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api delete user params
func (o *APIDeleteUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api delete user params
func (o *APIDeleteUserParams) WithHTTPClient(client *http.Client) *APIDeleteUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api delete user params
func (o *APIDeleteUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the Api delete user params
func (o *APIDeleteUserParams) WithID(id string) *APIDeleteUserParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the Api delete user params
func (o *APIDeleteUserParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *APIDeleteUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
