// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbCreateUserReq pb create user req
//
// swagger:model pbCreateUserReq
type PbCreateUserReq struct {

	// Email
	// Example: username@example.com
	Email string `json:"email,omitempty"`

	// Name
	// Example: username
	Name string `json:"name,omitempty"`
}

// Validate validates this pb create user req
func (m *PbCreateUserReq) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb create user req based on context it is used
func (m *PbCreateUserReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbCreateUserReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbCreateUserReq) UnmarshalBinary(b []byte) error {
	var res PbCreateUserReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
