// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PbToken pb token
//
// swagger:model pbToken
type PbToken struct {

	// token string
	TokenString string `json:"tokenString,omitempty"`
}

// Validate validates this pb token
func (m *PbToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pb token based on context it is used
func (m *PbToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PbToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PbToken) UnmarshalBinary(b []byte) error {
	var res PbToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
