// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/skunkie/grpc-gateway-example/pkg/httpclient/models"
)

// NewAPICreateTokenParams creates a new APICreateTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAPICreateTokenParams() *APICreateTokenParams {
	return &APICreateTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAPICreateTokenParamsWithTimeout creates a new APICreateTokenParams object
// with the ability to set a timeout on a request.
func NewAPICreateTokenParamsWithTimeout(timeout time.Duration) *APICreateTokenParams {
	return &APICreateTokenParams{
		timeout: timeout,
	}
}

// NewAPICreateTokenParamsWithContext creates a new APICreateTokenParams object
// with the ability to set a context for a request.
func NewAPICreateTokenParamsWithContext(ctx context.Context) *APICreateTokenParams {
	return &APICreateTokenParams{
		Context: ctx,
	}
}

// NewAPICreateTokenParamsWithHTTPClient creates a new APICreateTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewAPICreateTokenParamsWithHTTPClient(client *http.Client) *APICreateTokenParams {
	return &APICreateTokenParams{
		HTTPClient: client,
	}
}

/*
APICreateTokenParams contains all the parameters to send to the API endpoint

	for the Api create token operation.

	Typically these are written to a http.Request.
*/
type APICreateTokenParams struct {

	// Body.
	Body *models.PbCreateTokenReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the Api create token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APICreateTokenParams) WithDefaults() *APICreateTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the Api create token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APICreateTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the Api create token params
func (o *APICreateTokenParams) WithTimeout(timeout time.Duration) *APICreateTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api create token params
func (o *APICreateTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api create token params
func (o *APICreateTokenParams) WithContext(ctx context.Context) *APICreateTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api create token params
func (o *APICreateTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api create token params
func (o *APICreateTokenParams) WithHTTPClient(client *http.Client) *APICreateTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api create token params
func (o *APICreateTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the Api create token params
func (o *APICreateTokenParams) WithBody(body *models.PbCreateTokenReq) *APICreateTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the Api create token params
func (o *APICreateTokenParams) SetBody(body *models.PbCreateTokenReq) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *APICreateTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
